In [5]:
import pandas as pd
import numpy as np
import os
datadir = os.path.abspath('..')+"/data/GBIFData.csv"
gbifdata=pd.read_csv(datadir)

/home/nickpichome/miniconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
gbifdata.head(10)

,family,genus,species,taxonrank,countrycode,locality,taxonkey,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Mussidae,Favia,Favia fragum,SPECIES,1795),TT,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Siderastreidae,Siderastrea,Siderastrea siderea,SPECIES,1768),TT,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Poritidae,Porites,Porites porites,SPECIES,1766),TT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mussidae,Favia,Favia fragum,SPECIES,1795),TT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Acroporidae,Acropora,Acropora palmata,SPECIES,1816),TT,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Siderastreidae,Siderastrea,Siderastrea radians,SPECIES,1766),TT,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Siderastreidae,Siderastrea,Siderastrea siderea,SPECIES,1768),TT,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Siderastreidae,Siderastrea,Siderastrea siderea,SPECIES,1768),TT,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Siderastreidae,Siderastrea,Siderastrea siderea,SPECIES,1768),TT,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Siderastreidae,Siderastrea,Siderastrea siderea,SPECIES,1768),TT,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN